-- MySQL Script generated by MySQL Workbench
-- mer. 09 janv. 2019 12:13:07 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema okanban
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema okanban
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `okanban` DEFAULT CHARACTER SET utf8 ;
USE `okanban` ;

-- -----------------------------------------------------
-- Table `okanban`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `okanban`.`list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `order` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okanban`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `okanban`.`card` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `order` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `color` VARCHAR(6) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `list_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_list_idx` (`list_id` ASC),
  CONSTRAINT `fk_card_list`
    FOREIGN KEY (`list_id`)
    REFERENCES `okanban`.`list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okanban`.`label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `okanban`.`label` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `okanban`.`card_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `okanban`.`card_label` (
  `card_id` INT UNSIGNED NOT NULL,
  `label_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`card_id`, `label_id`),
  INDEX `fk_card_has_label_label1_idx` (`label_id` ASC),
  INDEX `fk_card_has_label_card1_idx` (`card_id` ASC),
  CONSTRAINT `fk_card_has_label_card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `okanban`.`card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_has_label_label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `okanban`.`label` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
